apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: etterlevelse-alerts
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne
spec:
  receivers:
    slack:
      channel: etterlevelse-alerts
      prependText: '<!here> | '
    email:
      to: lord.andre.groseth@nav.no
      send_resolved: false
  alerts:
    - alert: Høy minne bruk
      expr: sum(container_memory_working_set_bytes{container="etterlevelse-backend", namespace="teamdatajegerne"}) > 980
      for: 2m
      description: "App {{ $labels.app }} har høy minne bruk i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: Høy cpu bruk
      expr: (sum(irate (container_cpu_usage_seconds_total{container="etterlevelse-backend"}[1m])) * 1000) > 980
      for: 3m
      description: "App {{ $labels.app }} har høy cpu bruk i namespace {{ $labels.kubernetes_namespace }}"
      action: "Sjekk grafana og logene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}."
