export const omPVKUrl: string = '/om-pvk'
export const oversiktOverLosningeneUrl: string = '/oversikt-over-losningene'
export const omStotteTilEtterlevelseUrl: string = '/omstottetiletterlevelse'
export const omPersonvernerklaeringUrl: string = '/om-personvernerklaering'
export const omBehandlingskatalogenUrl: string = '/om-behandlingskatalogen'
