version: '4.1'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=etterlevelsedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql_16/data
    ports:
      - 5433:5432

volumes:
  postgres: