CREATE TABLE IF NOT EXISTS CODELIST
(
    LIST_NAME          TEXT      NOT NULL,
    CODE               TEXT      NOT NULL,
    SHORT_NAME         TEXT      NOT NULL,
    DESCRIPTION        TEXT      NOT NULL,
    DATA               JSONB     NULL,
    VERSION            INTEGER   NOT NULL,
    CREATED_BY         TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   TEXT      NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    UNIQUE (LIST_NAME, CODE)
);