apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlevelse-frontend
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30

  accessPolicy:
    outbound:
      rules:
        - application: etterlevelse-backend
