client:
    behandlingskatalog:
        base-url: http://localhost:${wiremock.server.port:8080}/bkat
    teamcat:
        url: http://localhost:${wiremock.server.port:8080}/teamcat
    slack:
      base-url: http://localhost:${wiremock.server.port:8080}/slack

etterlev:
    security:
        enabled: false
        redirectUris: http://localhost:3000,http://localhost:8080

spring:
    main:
        allow-bean-definition-overriding: true
        lazy-initialization: true

DB_DATABASE: etterlevelsedb
DB_HOST: localhost
DB_PASSWORD: password
DB_PORT: 5433
DB_USERNAME: postgres

AZURE_APP_CLIENT_ID: 7a183a3e-f25a-4257-8f53-cb7151b3f6d1
AZURE_APP_CLIENT_SECRET: secret
AZURE_CLIENT_GROUPS_ADMIN: bf05a29f-6f80-4da1-b419-22c802fd41e7
AZURE_CLIENT_GROUPS: 2ee0ef50-718c-43d3-8c05-c839f2dc2490
AZURE_CLIENT_GROUPS_KRAVEIER: d99d875c-c028-46a4-94bc-a87a633b3eee
