name: Frontend-nextjs

on:
  push:
    paths:
      - ".github/workflows/etterlevelse-frontend-nextjs.yml"
      - "apps/frontend-nextjs/**"

defaults:
  run:
    working-directory: apps/frontend-nextjs

jobs:
  build:
    name: Frontend - build and push docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
      actions: read
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          
      - name: use dev config and dev favicon
        if: github.ref == 'refs/heads/master'
        run: |
          cp .env.dev .env
          cp ./public/faviconDev.svg ./public/favicon.svg

      - name: use prod config and prod favicon
        if: github.ref == 'refs/heads/prod'
        run: |
          cp .env.prod .env
          cp ./public/faviconProd.svg ./public/favicon.svg

      - name: add version
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: echo "REACT_APP_GIT_VERSION=${GITHUB_SHA}" >> .env

      - name: Build and push
        if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/master'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdatajegerne
          push_image: true
          image_suffix: frontend-nextjs
          docker_context: ./apps/frontend-nextjs

  deploy-preprod:
    name: Frontend - deploy Dev GCP
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/frontend-nextjs/nais/frontend-gcp.yaml
          VARS: apps/frontend-nextjs/nais/frontend-dev-gcp-vars.yaml
          ENVIRONMENT: dev-gcp:teamdatajegerne:etterlevelse-frontend-nextjs
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
